### ISSUE TITLE
Error getting repository info

### ISSUE THREAD

**Issue by Leon-Flor** [nikitacontreras/gitspy#1]
I tried to use the module, appending this:

```python
def main():
    urls = []
    writingUrls = True
    while (writingUrls):
        if len(urls) > 0:
            message.info(
                "Pana usted es muy canson por eso no tiene novia !!! 🤬")
        urls.append(input("\nWrite the url: "))
        writingUrls = input("Write another url? (y/n): ").lower() == "y"

    for url in urls:
        print(f"Processing {url}")
        repo = Repository(url)
        repo.init()
        message.success(f"Finished processing {url}")
``` 

But when I execute that, an error occurred

```
(base) ➜  gitspy git:(main) ✗ /opt/miniconda3/bin/python /Users/leonalejandroflorsandoval/Documents/gitspy/main.py

Write the url: https://demo.connectiva.com.co/welcome
Write another url? (y/n): y
[2024-11-07 18:01:19] [INFO] Pana usted es muy canson por eso no tiene novia !!! 🤬

Write the url: https://virtual.uniagraria.edu.co/.git/info/
Write another url? (y/n): n
[2024-11-07 18:02:07] [INFO] Checking if https://demo.connectiva.com.co has a .git folder
[2024-11-07 18:02:08] [SUCCESS] demo.connectiva.com.co has a valid git folder
[2024-11-07 18:02:08] [INFO] demo.connectiva.com.co has directory listing
[2024-11-07 18:02:08] [LOG] Getting repository info
[2024-11-07 18:02:08] [INFO] Downloading [.git/config]...
Traceback (most recent call last):
  File "/Users/leonalejandroflorsandoval/Documents/gitspy/main.py", line 52, in <module>
    main()
  File "/Users/leonalejandroflorsandoval/Documents/gitspy/main.py", line 47, in main
    repo.init()
  File "/Users/leonalejandroflorsandoval/Documents/gitspy/main.py", line 15, in init
    self.process_remote_repo()
  File "/Users/leonalejandroflorsandoval/Documents/gitspy/main.py", line 31, in process_remote_repo
    self.gitweb.files.config
  File "/Users/leonalejandroflorsandoval/Documents/gitspy/tools/git.py", line 245, in config
    config.read_string(data.decode("utf-8"))
  File "/opt/miniconda3/lib/python3.12/configparser.py", line 710, in read_string
    self.read_file(sfile, source)
  File "/opt/miniconda3/lib/python3.12/configparser.py", line 705, in read_file
    self._read(f, source)
  File "/opt/miniconda3/lib/python3.12/configparser.py", line 1064, in _read
    raise MissingSectionHeaderError(fpname, lineno, line)
configparser.MissingSectionHeaderError: File contains no section headers.
file: '<string>', line: 1
'<!doctype html>\n'
(base) ➜  gitspy git:(main) ✗ /opt/miniconda3/bin/python /Users/leonalejandroflorsandoval/Documents/gitspy/main.py
```

**Comment by Leon-Flor** [comment]
Please review that, I am waiting to can use

**Comment by nikitacontreras** [comment]
solucionado, se me olvidó cerrar

mejor tarde que nunca jijijiji
